<?php

namespace Database\Seeders;

use App\Enums\UserRoleType;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Spatie\Permission\PermissionRegistrar;

class RolePermissionSeeder extends Seeder
{
    public function run(): void
    {
        app()[PermissionRegistrar::class]->forgetCachedPermissions();

        $permissions = [
            'users.view',
            'users.create',
            'users.update',
            'users.delete',
            'users.manage-roles',
            'students.view',
            'students.create',
            'students.update',
            'students.delete',
            'classes.view',
            'classes.create',
            'classes.update',
            'classes.delete',
            'lessons.view',
            'lessons.create',
            'lessons.update',
            'lessons.delete',
            'schools.view',
            'schools.create',
            'schools.update',
            'schools.delete',
            'academic_fields.view',
            'academic_fields.create',
            'academic_fields.update',
            'academic_fields.delete',
            'academic_levels.view',
            'academic_levels.create',
            'academic_levels.update',
            'academic_levels.delete',
            'student_registrations.view',
            'student_registrations.create',
            'student_registrations.delete',
            'student_profiles.view',
            'student_profiles.create',
            'student_profiles.update',
            'student_profiles.delete',
            'student_guardians.view',
            'student_guardians.create',
            'student_guardians.update',
            'student_guardians.delete',
            'exam_categories.view',
            'exam_categories.create',
            'exam_categories.update',
            'exam_categories.delete',
            'exams.view',
            'exams.create',
            'exams.update',
            'exams.delete',
            'grades.view',
            'grades.create',
            'grades.update',
            'grades.delete',
            'homework.view',
            'homework.create',
            'homework.update',
            'homework.delete',
            'homework_submissions.view',
            'homework_submissions.create',
            'homework_submissions.update',
            'homework_submissions.delete',
            'disciplinary_cases.view',
            'disciplinary_cases.create',
            'disciplinary_cases.update',
            'disciplinary_cases.delete',
            'disciplinary_records.view',
            'disciplinary_records.create',
            'disciplinary_records.update',
            'disciplinary_records.delete',
            'messages.view',
            'messages.create',
            'messages.update',
            'messages.delete',
        ];

        foreach ($permissions as $permission) {
            Permission::firstOrCreate(['name' => $permission], ['guard_name' => 'web']);
        }

        $admin = Role::findOrCreate(UserRoleType::Admin->value, 'web');
        $manager = Role::findOrCreate(UserRoleType::Manager->value, 'web');
        $teacher = Role::findOrCreate(UserRoleType::Teacher->value, 'web');
        $student = Role::findOrCreate(UserRoleType::Student->value, 'web');
        $staff = Role::findOrCreate(UserRoleType::Staff->value, 'web');
        $guardian = Role::findOrCreate(UserRoleType::Guardian->value, 'web');

        $admin->syncPermissions($permissions);

        $manager->syncPermissions([
            'users.view',
            'students.view',
            'students.create',
            'students.update',
            'students.delete',
            'classes.view',
            'classes.create',
            'classes.update',
            'classes.delete',
            'lessons.view',
            'lessons.create',
            'lessons.update',
            'lessons.delete',
            'schools.view',
            'schools.create',
            'schools.update',
            'schools.delete',
            'academic_fields.view',
            'academic_fields.create',
            'academic_fields.update',
            'academic_fields.delete',
            'academic_levels.view',
            'academic_levels.create',
            'academic_levels.update',
            'academic_levels.delete',
            'student_registrations.view',
            'student_registrations.create',
            'student_registrations.delete',
            'student_profiles.view',
            'student_profiles.create',
            'student_profiles.update',
            'student_profiles.delete',
            'student_guardians.view',
            'student_guardians.create',
            'student_guardians.update',
            'student_guardians.delete',
            'exam_categories.view',
            'exam_categories.create',
            'exam_categories.update',
            'exam_categories.delete',
            'exams.view',
            'exams.create',
            'exams.update',
            'exams.delete',
            'grades.view',
            'grades.create',
            'grades.update',
            'grades.delete',
            'homework.view',
            'homework.create',
            'homework.update',
            'homework.delete',
            'homework_submissions.view',
            'homework_submissions.create',
            'homework_submissions.update',
            'homework_submissions.delete',
            'disciplinary_cases.view',
            'disciplinary_cases.create',
            'disciplinary_cases.update',
            'disciplinary_cases.delete',
            'disciplinary_records.view',
            'disciplinary_records.create',
            'disciplinary_records.update',
            'disciplinary_records.delete',
            'messages.view',
            'messages.create',
            'messages.update',
            'messages.delete',
        ]);

        $teacher->syncPermissions([
            'students.view',
            'classes.view',
            'lessons.view',
            'exam_categories.view',
            'exams.view',
            'exams.create',
            'exams.update',
            'exams.delete',
            'grades.view',
            'grades.create',
            'grades.update',
            'grades.delete',
            'homework.view',
            'homework.create',
            'homework.update',
            'homework.delete',
            'homework_submissions.view',
            'homework_submissions.create',
            'homework_submissions.update',
            'homework_submissions.delete',
            'disciplinary_cases.view',
            'disciplinary_cases.create',
            'disciplinary_cases.update',
            'disciplinary_cases.delete',
            'disciplinary_records.view',
            'disciplinary_records.create',
            'disciplinary_records.update',
            'disciplinary_records.delete',
            'messages.view',
            'messages.create',
            'messages.update',
            'messages.delete',
        ]);

        $student->syncPermissions([
            'students.view',
            'grades.view',
            'exams.view',
            'homework.view',
            'homework_submissions.view',
            'homework_submissions.create',
            'disciplinary_cases.view',
            'disciplinary_records.view',
            'messages.view',
            'messages.create',
        ]);
        $guardian->syncPermissions([
            'students.view',
            'grades.view',
            'exams.view',
            'homework.view',
            'homework_submissions.view',
            'disciplinary_cases.view',
            'disciplinary_records.view',
            'messages.view',
            'messages.create',
        ]);

        $staff->syncPermissions([
            'students.view',
            'classes.view',
            'lessons.view',
            'exams.view',
            'grades.view',
            'homework.view',
            'homework_submissions.view',
            'disciplinary_cases.view',
            'disciplinary_records.view',
            'messages.view',
            'messages.create',
        ]);
    }
}
