<?php

namespace Database\Seeders;

use App\Enums\UserRoleType;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Spatie\Permission\PermissionRegistrar;

class RolePermissionSeeder extends Seeder
{
    public function run(): void
    {
        app()[PermissionRegistrar::class]->forgetCachedPermissions();

        $permissions = [
            'users.view',
            'users.create',
            'users.update',
            'users.delete',
            'users.manage-roles',
            'tags.view',
            'tags.create',
            'tags.update',
            'tags.delete',
            'places.view',
            'places.create',
            'places.update',
            'places.delete',
            'places.import',
            'places.manage-tags',
            'students.view',
            'students.create',
            'students.update',
            'students.delete',
            'classes.view',
            'classes.create',
            'classes.update',
            'classes.delete',
            'lessons.view',
            'lessons.create',
            'lessons.update',
            'lessons.delete',
            'exams.view',
            'exams.create',
            'exams.update',
            'exams.delete',
            'grades.view',
            'grades.create',
            'grades.update',
            'grades.delete',
            'quizzes.view',
            'quizzes.create',
            'quizzes.update',
            'quizzes.delete',
            'quizzes.manage',
            'quiz_sessions.view',
            'quiz_sessions.create',
            'quiz_sessions.update',
            'quiz_sessions.delete',
            'homework.view',
            'homework.create',
            'homework.update',
            'homework.delete',
            'homework_submissions.view',
            'homework_submissions.create',
            'homework_submissions.update',
            'homework_submissions.delete',
            'quiz_assignments.view',
            'quiz_assignments.create',
            'quiz_assignments.update',
            'quiz_assignments.delete',
            'disciplinary_cases.view',
            'disciplinary_cases.create',
            'disciplinary_cases.update',
            'disciplinary_cases.delete',
            'disciplinary_records.view',
            'disciplinary_records.create',
            'disciplinary_records.update',
            'disciplinary_records.delete',
            'messages.view',
            'messages.create',
            'messages.update',
            'messages.delete',
            'academic_fields.view',
            'academic_fields.create',
            'academic_fields.update',
            'academic_fields.delete',
            'academic_levels.view',
            'academic_levels.create',
            'academic_levels.update',
            'academic_levels.delete',
            'schools.view',
            'schools.create',
            'schools.update',
            'schools.delete',
            'student_registrations.view',
            'student_registrations.create',
            'student_registrations.delete',
            'pre_registrations.view',
            'pre_registrations.create',
        ];

        foreach ($permissions as $permission) {
            Permission::firstOrCreate(['name' => $permission], ['guard_name' => 'web']);
        }

        $admin = Role::findOrCreate(UserRoleType::Admin->value, 'web');
        $manager = Role::findOrCreate(UserRoleType::Manager->value, 'web');
        $user = Role::findOrCreate(UserRoleType::User->value, 'web');
        $teacher = Role::findOrCreate('teacher', 'web');
        $student = Role::findOrCreate('student', 'web');

        $admin->syncPermissions($permissions);

        $manager->syncPermissions([
            'users.view',
            'tags.view',
            'tags.create',
            'tags.update',
            'tags.delete',
            'places.view',
            'places.create',
            'places.update',
            'places.delete',
            'places.import',
            'places.manage-tags',
            'students.view',
            'students.create',
            'students.update',
            'students.delete',
            'classes.view',
            'classes.create',
            'classes.update',
            'classes.delete',
            'lessons.view',
            'lessons.create',
            'lessons.update',
            'lessons.delete',
            'exams.view',
            'exams.create',
            'exams.update',
            'exams.delete',
            'grades.view',
            'grades.create',
            'grades.update',
            'grades.delete',
            'quizzes.view',
            'quizzes.create',
            'quizzes.update',
            'quizzes.delete',
            'quizzes.manage',
            'quiz_sessions.view',
            'quiz_sessions.create',
            'quiz_sessions.update',
            'quiz_sessions.delete',
            'quiz_assignments.view',
            'quiz_assignments.create',
            'quiz_assignments.update',
            'quiz_assignments.delete',
            'homework.view',
            'homework.create',
            'homework.update',
            'homework.delete',
            'homework_submissions.view',
            'homework_submissions.create',
            'homework_submissions.update',
            'homework_submissions.delete',
            'disciplinary_cases.view',
            'disciplinary_cases.create',
            'disciplinary_cases.update',
            'disciplinary_cases.delete',
            'disciplinary_records.view',
            'disciplinary_records.create',
            'disciplinary_records.update',
            'disciplinary_records.delete',
            'messages.view',
            'messages.create',
            'messages.update',
            'messages.delete',
            'academic_fields.view',
            'academic_fields.create',
            'academic_fields.update',
            'academic_fields.delete',
            'academic_levels.view',
            'academic_levels.create',
            'academic_levels.update',
            'academic_levels.delete',
            'schools.view',
            'schools.create',
            'schools.update',
            'schools.delete',
            'student_registrations.view',
            'student_registrations.create',
            'student_registrations.delete',
            'pre_registrations.view',
            'pre_registrations.create',
        ]);

        $teacher->syncPermissions([
            'students.view',
            'classes.view',
            'lessons.view',
            'exams.view',
            'exams.create',
            'grades.view',
            'grades.create',
            'grades.update',
            'grades.delete',
            'quizzes.view',
            'quizzes.create',
            'quizzes.update',
            'quizzes.delete',
            'quizzes.manage',
            'quiz_sessions.view',
            'quiz_sessions.create',
            'quiz_sessions.update',
            'quiz_sessions.delete',
            'quiz_assignments.view',
            'quiz_assignments.create',
            'quiz_assignments.update',
            'quiz_assignments.delete',
            'homework.view',
            'homework.create',
            'homework.update',
            'homework.delete',
            'homework_submissions.view',
            'homework_submissions.create',
            'homework_submissions.update',
            'homework_submissions.delete',
            'disciplinary_cases.view',
            'disciplinary_cases.create',
            'disciplinary_cases.update',
            'disciplinary_cases.delete',
            'disciplinary_records.view',
            'disciplinary_records.create',
            'disciplinary_records.update',
            'disciplinary_records.delete',
            'messages.view',
            'messages.create',
            'messages.update',
            'messages.delete',
        ]);

        $student->syncPermissions([
            'students.view',
            'grades.view',
            'quizzes.view',
            'quiz_sessions.view',
            'homework.view',
            'homework_submissions.view',
            'homework_submissions.create',
            'disciplinary_cases.view',
            'disciplinary_records.view',
            'messages.view',
            'messages.create',
        ]);

        $user->syncPermissions([
            'tags.view',
            'places.view',
            'places.manage-tags',
        ]);
    }
}